export interface MissileSpec {
  id: string;
  name: string;
  country: string;
  category: string;
  exhaustVelocity: number;
  massFlowRate: number;
  fuelMass: number;
  payloadMass: number;
  startInclineAfterDistance: number;
  thrustInclineMaxDuration: number;
  thrustInclineVelocityDeg: number;
}

export const MISSILE_CATEGORIES = [
  'ICBM',
  'Hypersonic',
  'IRBM',
  'MRBM',
  'SRBM',
  'Cruise Missile',
  'Anti-Ship',
] as const;

export const MISSILES: MissileSpec[] = [
  // ─── US ───
  {
    id: 'us_minuteman3',
    name: 'LGM-30 Minuteman III',
    country: 'US',
    category: 'ICBM',
    exhaustVelocity: 2.8,
    massFlowRate: 70,
    fuelMass: 35000,
    payloadMass: 1100,
    startInclineAfterDistance: 2,
    thrustInclineMaxDuration: 200,
    thrustInclineVelocityDeg: 0.5,
  },
  {
    id: 'us_sentinel',
    name: 'LGM-35 Sentinel',
    country: 'US',
    category: 'ICBM',
    exhaustVelocity: 2.9,
    massFlowRate: 75,
    fuelMass: 38000,
    payloadMass: 1200,
    startInclineAfterDistance: 2,
    thrustInclineMaxDuration: 210,
    thrustInclineVelocityDeg: 0.5,
  },
  {
    id: 'us_trident2',
    name: 'UGM-133 Trident II (SLBM)',
    country: 'US',
    category: 'ICBM',
    exhaustVelocity: 2.7,
    massFlowRate: 65,
    fuelMass: 32000,
    payloadMass: 1800,
    startInclineAfterDistance: 2,
    thrustInclineMaxDuration: 190,
    thrustInclineVelocityDeg: 0.6,
  },
  {
    id: 'us_arrw',
    name: 'AGM-183 ARRW (Hypersonic)',
    country: 'US',
    category: 'Hypersonic',
    exhaustVelocity: 3.5,
    massFlowRate: 40,
    fuelMass: 5000,
    payloadMass: 300,
    startInclineAfterDistance: 3,
    thrustInclineMaxDuration: 60,
    thrustInclineVelocityDeg: 2.0,
  },
  {
    id: 'us_dark_eagle',
    name: 'LRHW Dark Eagle (Hypersonic)',
    country: 'US',
    category: 'Hypersonic',
    exhaustVelocity: 3.8,
    massFlowRate: 50,
    fuelMass: 7000,
    payloadMass: 400,
    startInclineAfterDistance: 3,
    thrustInclineMaxDuration: 80,
    thrustInclineVelocityDeg: 2.0,
  },
  {
    id: 'us_tomahawk',
    name: 'BGM-109 Tomahawk (Cruise)',
    country: 'US',
    category: 'Cruise Missile',
    exhaustVelocity: 2.0,
    massFlowRate: 20,
    fuelMass: 4000,
    payloadMass: 500,
    startInclineAfterDistance: 1,
    thrustInclineMaxDuration: 30,
    thrustInclineVelocityDeg: 3.0,
  },
  {
    id: 'us_atacms',
    name: 'MGM-140 ATACMS (SRBM)',
    country: 'US',
    category: 'SRBM',
    exhaustVelocity: 2.4,
    massFlowRate: 30,
    fuelMass: 6000,
    payloadMass: 600,
    startInclineAfterDistance: 1,
    thrustInclineMaxDuration: 40,
    thrustInclineVelocityDeg: 1.5,
  },

  // ─── Russia ───
  {
    id: 'ru_sarmat',
    name: 'RS-28 Sarmat (SS-30)',
    country: 'Russia',
    category: 'ICBM',
    exhaustVelocity: 3.2,
    massFlowRate: 85,
    fuelMass: 78000,
    payloadMass: 2000,
    startInclineAfterDistance: 2,
    thrustInclineMaxDuration: 250,
    thrustInclineVelocityDeg: 0.4,
  },
  {
    id: 'ru_satan',
    name: 'R-36M2 Voevoda (SS-18 Satan)',
    country: 'Russia',
    category: 'ICBM',
    exhaustVelocity: 3.1,
    massFlowRate: 80,
    fuelMass: 65000,
    payloadMass: 1800,
    startInclineAfterDistance: 2,
    thrustInclineMaxDuration: 240,
    thrustInclineVelocityDeg: 0.4,
  },
  {
    id: 'ru_yars',
    name: 'RS-24 Yars (SS-27 Mod 2)',
    country: 'Russia',
    category: 'ICBM',
    exhaustVelocity: 2.9,
    massFlowRate: 70,
    fuelMass: 40000,
    payloadMass: 1200,
    startInclineAfterDistance: 2,
    thrustInclineMaxDuration: 200,
    thrustInclineVelocityDeg: 0.5,
  },
  {
    id: 'ru_topolm',
    name: 'RT-2PM2 Topol-M (SS-27)',
    country: 'Russia',
    category: 'ICBM',
    exhaustVelocity: 2.8,
    massFlowRate: 65,
    fuelMass: 38000,
    payloadMass: 1100,
    startInclineAfterDistance: 2,
    thrustInclineMaxDuration: 190,
    thrustInclineVelocityDeg: 0.5,
  },
  {
    id: 'ru_avangard',
    name: 'Avangard (Hypersonic Glide)',
    country: 'Russia',
    category: 'Hypersonic',
    exhaustVelocity: 4.0,
    massFlowRate: 55,
    fuelMass: 8000,
    payloadMass: 500,
    startInclineAfterDistance: 3,
    thrustInclineMaxDuration: 90,
    thrustInclineVelocityDeg: 2.5,
  },
  {
    id: 'ru_zircon',
    name: '3M22 Zircon (Hypersonic ASM)',
    country: 'Russia',
    category: 'Anti-Ship',
    exhaustVelocity: 3.8,
    massFlowRate: 45,
    fuelMass: 6000,
    payloadMass: 400,
    startInclineAfterDistance: 3,
    thrustInclineMaxDuration: 50,
    thrustInclineVelocityDeg: 3.0,
  },
  {
    id: 'ru_kinzhal',
    name: 'Kh-47M2 Kinzhal (Hypersonic)',
    country: 'Russia',
    category: 'Hypersonic',
    exhaustVelocity: 3.6,
    massFlowRate: 42,
    fuelMass: 5500,
    payloadMass: 350,
    startInclineAfterDistance: 3,
    thrustInclineMaxDuration: 70,
    thrustInclineVelocityDeg: 2.5,
  },
  {
    id: 'ru_iskander',
    name: '9K720 Iskander-M (SRBM)',
    country: 'Russia',
    category: 'SRBM',
    exhaustVelocity: 2.5,
    massFlowRate: 35,
    fuelMass: 8000,
    payloadMass: 700,
    startInclineAfterDistance: 1,
    thrustInclineMaxDuration: 50,
    thrustInclineVelocityDeg: 1.5,
  },

  // ─── China ───
  {
    id: 'cn_df41',
    name: 'DF-41 (CSS-20)',
    country: 'China',
    category: 'ICBM',
    exhaustVelocity: 3.0,
    massFlowRate: 75,
    fuelMass: 58000,
    payloadMass: 1800,
    startInclineAfterDistance: 2,
    thrustInclineMaxDuration: 230,
    thrustInclineVelocityDeg: 0.45,
  },
  {
    id: 'cn_df5',
    name: 'DF-5 (CSS-4)',
    country: 'China',
    category: 'ICBM',
    exhaustVelocity: 2.9,
    massFlowRate: 70,
    fuelMass: 52000,
    payloadMass: 1500,
    startInclineAfterDistance: 2,
    thrustInclineMaxDuration: 220,
    thrustInclineVelocityDeg: 0.45,
  },
  {
    id: 'cn_df31',
    name: 'DF-31 (CSS-10)',
    country: 'China',
    category: 'ICBM',
    exhaustVelocity: 2.8,
    massFlowRate: 60,
    fuelMass: 35000,
    payloadMass: 1100,
    startInclineAfterDistance: 2,
    thrustInclineMaxDuration: 190,
    thrustInclineVelocityDeg: 0.5,
  },
  {
    id: 'cn_df17',
    name: 'DF-17 (Hypersonic Glide)',
    country: 'China',
    category: 'Hypersonic',
    exhaustVelocity: 3.6,
    massFlowRate: 48,
    fuelMass: 7500,
    payloadMass: 450,
    startInclineAfterDistance: 3,
    thrustInclineMaxDuration: 85,
    thrustInclineVelocityDeg: 2.0,
  },
  {
    id: 'cn_df21d',
    name: 'DF-21D (Carrier Killer)',
    country: 'China',
    category: 'IRBM',
    exhaustVelocity: 2.6,
    massFlowRate: 45,
    fuelMass: 15000,
    payloadMass: 800,
    startInclineAfterDistance: 2,
    thrustInclineMaxDuration: 120,
    thrustInclineVelocityDeg: 0.8,
  },
  {
    id: 'cn_yj18',
    name: 'YJ-18 (Supersonic ASM)',
    country: 'China',
    category: 'Anti-Ship',
    exhaustVelocity: 2.8,
    massFlowRate: 30,
    fuelMass: 4000,
    payloadMass: 300,
    startInclineAfterDistance: 2,
    thrustInclineMaxDuration: 40,
    thrustInclineVelocityDeg: 2.0,
  },

  // ─── India ───
  {
    id: 'in_agni5',
    name: 'Agni-V',
    country: 'India',
    category: 'ICBM',
    exhaustVelocity: 2.6,
    massFlowRate: 55,
    fuelMass: 25000,
    payloadMass: 1000,
    startInclineAfterDistance: 2,
    thrustInclineMaxDuration: 170,
    thrustInclineVelocityDeg: 0.55,
  },
  {
    id: 'in_agni4',
    name: 'Agni-IV',
    country: 'India',
    category: 'IRBM',
    exhaustVelocity: 2.5,
    massFlowRate: 45,
    fuelMass: 16000,
    payloadMass: 800,
    startInclineAfterDistance: 2,
    thrustInclineMaxDuration: 130,
    thrustInclineVelocityDeg: 0.7,
  },
  {
    id: 'in_agni2',
    name: 'Agni-II',
    country: 'India',
    category: 'IRBM',
    exhaustVelocity: 2.4,
    massFlowRate: 38,
    fuelMass: 12000,
    payloadMass: 700,
    startInclineAfterDistance: 2,
    thrustInclineMaxDuration: 110,
    thrustInclineVelocityDeg: 0.8,
  },
  {
    id: 'in_agni1',
    name: 'Agni-I',
    country: 'India',
    category: 'SRBM',
    exhaustVelocity: 2.3,
    massFlowRate: 28,
    fuelMass: 6000,
    payloadMass: 500,
    startInclineAfterDistance: 1,
    thrustInclineMaxDuration: 60,
    thrustInclineVelocityDeg: 1.2,
  },
  {
    id: 'in_prithvi2',
    name: 'Prithvi-II',
    country: 'India',
    category: 'SRBM',
    exhaustVelocity: 2.2,
    massFlowRate: 22,
    fuelMass: 4000,
    payloadMass: 500,
    startInclineAfterDistance: 1,
    thrustInclineMaxDuration: 45,
    thrustInclineVelocityDeg: 1.5,
  },
  {
    id: 'in_hstdv',
    name: 'HSTDV (Hypersonic)',
    country: 'India',
    category: 'Hypersonic',
    exhaustVelocity: 3.4,
    massFlowRate: 38,
    fuelMass: 4500,
    payloadMass: 250,
    startInclineAfterDistance: 3,
    thrustInclineMaxDuration: 65,
    thrustInclineVelocityDeg: 2.0,
  },
  {
    id: 'in_brahmos',
    name: 'BrahMos (Supersonic ASM)',
    country: 'India',
    category: 'Anti-Ship',
    exhaustVelocity: 2.6,
    massFlowRate: 28,
    fuelMass: 3000,
    payloadMass: 300,
    startInclineAfterDistance: 2,
    thrustInclineMaxDuration: 35,
    thrustInclineVelocityDeg: 2.5,
  },

  // ─── Turkey ───
  {
    id: 'tr_bora',
    name: 'BORA (SRBM)',
    country: 'Turkey',
    category: 'SRBM',
    exhaustVelocity: 2.3,
    massFlowRate: 25,
    fuelMass: 5000,
    payloadMass: 500,
    startInclineAfterDistance: 1,
    thrustInclineMaxDuration: 50,
    thrustInclineVelocityDeg: 1.5,
  },
  {
    id: 'tr_tayfun',
    name: 'TAYFUN (SRBM)',
    country: 'Turkey',
    category: 'SRBM',
    exhaustVelocity: 2.4,
    massFlowRate: 30,
    fuelMass: 7000,
    payloadMass: 600,
    startInclineAfterDistance: 1,
    thrustInclineMaxDuration: 55,
    thrustInclineVelocityDeg: 1.5,
  },
  {
    id: 'tr_som',
    name: 'SOM-J (Cruise Missile)',
    country: 'Turkey',
    category: 'Cruise Missile',
    exhaustVelocity: 2.0,
    massFlowRate: 18,
    fuelMass: 3000,
    payloadMass: 400,
    startInclineAfterDistance: 1,
    thrustInclineMaxDuration: 25,
    thrustInclineVelocityDeg: 3.0,
  },
  {
    id: 'tr_atmaca',
    name: 'ATMACA (Anti-Ship)',
    country: 'Turkey',
    category: 'Anti-Ship',
    exhaustVelocity: 2.2,
    massFlowRate: 20,
    fuelMass: 2500,
    payloadMass: 300,
    startInclineAfterDistance: 1,
    thrustInclineMaxDuration: 30,
    thrustInclineVelocityDeg: 2.5,
  },
  {
    id: 'tr_kara_atmaca',
    name: 'KARA ATMACA (Cruise)',
    country: 'Turkey',
    category: 'Cruise Missile',
    exhaustVelocity: 2.1,
    massFlowRate: 20,
    fuelMass: 3500,
    payloadMass: 400,
    startInclineAfterDistance: 1,
    thrustInclineMaxDuration: 28,
    thrustInclineVelocityDeg: 2.5,
  },
  {
    id: 'tr_ceyhan',
    name: 'CEYHAN (Hypersonic - in dev)',
    country: 'Turkey',
    category: 'Hypersonic',
    exhaustVelocity: 3.2,
    massFlowRate: 35,
    fuelMass: 5000,
    payloadMass: 300,
    startInclineAfterDistance: 3,
    thrustInclineMaxDuration: 70,
    thrustInclineVelocityDeg: 2.0,
  },

  // ─── Europe ───
  {
    id: 'fr_m51',
    name: 'M51 (SLBM - France)',
    country: 'Europe',
    category: 'ICBM',
    exhaustVelocity: 2.9,
    massFlowRate: 68,
    fuelMass: 48000,
    payloadMass: 1500,
    startInclineAfterDistance: 2,
    thrustInclineMaxDuration: 220,
    thrustInclineVelocityDeg: 0.45,
  },
  {
    id: 'fr_asmpa',
    name: 'ASMP-A (Air-Launched - France)',
    country: 'Europe',
    category: 'Hypersonic',
    exhaustVelocity: 3.2,
    massFlowRate: 35,
    fuelMass: 4000,
    payloadMass: 300,
    startInclineAfterDistance: 3,
    thrustInclineMaxDuration: 55,
    thrustInclineVelocityDeg: 2.0,
  },
  {
    id: 'eu_stormshadow',
    name: 'Storm Shadow / SCALP (Cruise)',
    country: 'Europe',
    category: 'Cruise Missile',
    exhaustVelocity: 2.0,
    massFlowRate: 16,
    fuelMass: 2500,
    payloadMass: 450,
    startInclineAfterDistance: 1,
    thrustInclineMaxDuration: 22,
    thrustInclineVelocityDeg: 3.0,
  },
  {
    id: 'eu_taurus',
    name: 'Taurus KEPD 350 (Cruise)',
    country: 'Europe',
    category: 'Cruise Missile',
    exhaustVelocity: 2.1,
    massFlowRate: 18,
    fuelMass: 2800,
    payloadMass: 500,
    startInclineAfterDistance: 1,
    thrustInclineMaxDuration: 24,
    thrustInclineVelocityDeg: 3.0,
  },
  {
    id: 'fr_mbda_marte',
    name: 'MBDA Marte ER (Anti-Ship)',
    country: 'Europe',
    category: 'Anti-Ship',
    exhaustVelocity: 2.3,
    massFlowRate: 22,
    fuelMass: 2000,
    payloadMass: 250,
    startInclineAfterDistance: 1,
    thrustInclineMaxDuration: 28,
    thrustInclineVelocityDeg: 2.5,
  },

  // ─── Pakistan ───
  {
    id: 'pk_nasr',
    name: 'Nasr (Hatf-9) — 60 km',
    country: 'Pakistan',
    category: 'SRBM',
    exhaustVelocity: 2.0,
    massFlowRate: 15,
    fuelMass: 500,
    payloadMass: 120,
    startInclineAfterDistance: 0.5,
    thrustInclineMaxDuration: 20,
    thrustInclineVelocityDeg: 3.0,
  },
  {
    id: 'pk_abdali',
    name: 'Abdali (Hatf-2) — 180 km',
    country: 'Pakistan',
    category: 'SRBM',
    exhaustVelocity: 2.2,
    massFlowRate: 18,
    fuelMass: 1800,
    payloadMass: 300,
    startInclineAfterDistance: 1,
    thrustInclineMaxDuration: 35,
    thrustInclineVelocityDeg: 2.0,
  },
  {
    id: 'pk_ghaznavi',
    name: 'Ghaznavi (Hatf-3) — 290 km',
    country: 'Pakistan',
    category: 'SRBM',
    exhaustVelocity: 2.3,
    massFlowRate: 22,
    fuelMass: 3500,
    payloadMass: 450,
    startInclineAfterDistance: 1,
    thrustInclineMaxDuration: 45,
    thrustInclineVelocityDeg: 1.8,
  },
  {
    id: 'pk_shaheen1',
    name: 'Shaheen-1 (Hatf-4) — 750 km',
    country: 'Pakistan',
    category: 'MRBM',
    exhaustVelocity: 2.4,
    massFlowRate: 30,
    fuelMass: 7000,
    payloadMass: 600,
    startInclineAfterDistance: 2,
    thrustInclineMaxDuration: 60,
    thrustInclineVelocityDeg: 1.2,
  },
  {
    id: 'pk_ghauri',
    name: 'Ghauri (Hatf-5) — 1,300 km',
    country: 'Pakistan',
    category: 'MRBM',
    exhaustVelocity: 2.8,
    massFlowRate: 42,
    fuelMass: 12000,
    payloadMass: 700,
    startInclineAfterDistance: 2,
    thrustInclineMaxDuration: 100,
    thrustInclineVelocityDeg: 0.9,
  },
  {
    id: 'pk_shaheen2',
    name: 'Shaheen-2 (Hatf-6) — 2,000 km',
    country: 'Pakistan',
    category: 'IRBM',
    exhaustVelocity: 2.6,
    massFlowRate: 50,
    fuelMass: 18000,
    payloadMass: 700,
    startInclineAfterDistance: 2,
    thrustInclineMaxDuration: 140,
    thrustInclineVelocityDeg: 0.6,
  },
  {
    id: 'pk_babur',
    name: 'Babur (Hatf-7) — 700 km',
    country: 'Pakistan',
    category: 'Cruise Missile',
    exhaustVelocity: 2.0,
    massFlowRate: 18,
    fuelMass: 3000,
    payloadMass: 450,
    startInclineAfterDistance: 1,
    thrustInclineMaxDuration: 28,
    thrustInclineVelocityDeg: 3.0,
  },
  {
    id: 'pk_raad',
    name: "Ra'ad (Hatf-8) — 350 km",
    country: 'Pakistan',
    category: 'Cruise Missile',
    exhaustVelocity: 1.9,
    massFlowRate: 14,
    fuelMass: 1400,
    payloadMass: 250,
    startInclineAfterDistance: 1,
    thrustInclineMaxDuration: 22,
    thrustInclineVelocityDeg: 3.0,
  },
  {
    id: 'pk_shaheen3',
    name: 'Shaheen-3 — 2,750 km',
    country: 'Pakistan',
    category: 'IRBM',
    exhaustVelocity: 2.7,
    massFlowRate: 55,
    fuelMass: 22000,
    payloadMass: 600,
    startInclineAfterDistance: 2,
    thrustInclineMaxDuration: 180,
    thrustInclineVelocityDeg: 0.5,
  },
  {
    id: 'pk_ababeel',
    name: 'Ababeel — 2,200 km (MIRV)',
    country: 'Pakistan',
    category: 'ICBM',
    exhaustVelocity: 2.7,
    massFlowRate: 52,
    fuelMass: 20000,
    payloadMass: 800,
    startInclineAfterDistance: 2,
    thrustInclineMaxDuration: 160,
    thrustInclineVelocityDeg: 0.5,
  },
];

export function getMissileById(id: string): MissileSpec | undefined {
  return MISSILES.find((m) => m.id === id);
}

export function getMissilesByCategory(category: string): MissileSpec[] {
  return MISSILES.filter((m) => m.category === category);
}

export function getMissileOptions() {
  return MISSILES.map((m) => ({
    text: `${m.country} - ${m.name} (${m.category})`,
    value: m.id,
  }));
}
